import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            slug: 'seiko-ssk003k1',
            name: '5 Sports GMT Black',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK003K1',
            description: 'Reloj deportivo GMT con función de segunda zona horaria, ideal para viajeros.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Negro',
            waterResistance: '100m',
            price: 395,
            currency: 'EUR',
            stock: 5,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            slug: 'seiko-ssk001k1',
            name: '5 Sports GMT Blue',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK001K1',
            description: 'Versión azul del deportivo GMT, combinando estilo y funcionalidad.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Azul',
            waterResistance: '100m',
            price: 395,
            currency: 'EUR',
            stock: 4,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            slug: 'seiko-ssk005k1',
            name: '5 Sports GMT Green',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK005K1',
            description: 'Elegante versión verde del clásico deportivo GMT de Seiko.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Verde',
            waterResistance: '100m',
            price: 395,
            currency: 'EUR',
            stock: 3,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            slug: 'seiko-ssk021k1',
            name: '5 Sports GMT Special',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK021K1',
            description: 'Edición especial con bisel negro y rojo, diseño llamativo y deportivo.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Negro/Rojo',
            waterResistance: '100m',
            price: 425,
            currency: 'EUR',
            stock: 2,
            category: '5 Sports GMT',
            isNew: 1,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            slug: 'seiko-ssk035k1',
            name: '5 Sports GMT Urban',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK035K1',
            description: 'Diseño urbano en tono gris, perfecto para uso diario y viajes.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Gris',
            waterResistance: '100m',
            price: 410,
            currency: 'EUR',
            stock: 6,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            slug: 'seiko-ssk033k1',
            name: '5 Sports GMT White',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK033K1',
            description: 'Versión blanca elegante y versátil del deportivo GMT.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Blanco',
            waterResistance: '100m',
            price: 415,
            currency: 'EUR',
            stock: 4,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            slug: 'seiko-ssk031k1',
            name: '5 Sports GMT Champagne',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK031K1',
            description: 'Sofisticado diseño champagne para un look distintivo.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Champagne',
            waterResistance: '100m',
            price: 420,
            currency: 'EUR',
            stock: 3,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            slug: 'seiko-ssk029k1',
            name: '5 Sports GMT DLC',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK029K1',
            description: 'Acabado DLC negro premium para máxima resistencia y estilo.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Negro DLC',
            waterResistance: '100m',
            price: 445,
            currency: 'EUR',
            stock: 2,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            slug: 'seiko-ssk043k1',
            name: '5 Sports GMT Multicolor',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK043K1',
            description: 'Diseño vibrante multicolor que destaca en cualquier ocasión.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Multicolor',
            waterResistance: '100m',
            price: 430,
            currency: 'EUR',
            stock: 5,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            slug: 'seiko-ssk019k1',
            name: '5 Sports GMT Pepsi',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK019K1',
            description: 'Clásico bisel Pepsi en azul y rojo, icónico diseño GMT.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Azul/Rojo',
            waterResistance: '100m',
            price: 405,
            currency: 'EUR',
            stock: 7,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            slug: 'seiko-ssk017k1',
            name: '5 Sports GMT Batman',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK017K1',
            description: 'Bisel Batman en azul y negro, elegante y deportivo.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Azul/Negro',
            waterResistance: '100m',
            price: 410,
            currency: 'EUR',
            stock: 6,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            slug: 'seiko-ssk027k1',
            name: '5 Sports GMT Steel',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK027K1',
            description: 'Acabado en acero inoxidable completo, refinado y duradero.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Acero',
            waterResistance: '100m',
            price: 425,
            currency: 'EUR',
            stock: 3,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            slug: 'seiko-ssk044k1',
            name: '5 Sports GMT Adventure',
            brand: 'Seiko',
            series: '5 Sports GMT',
            reference: 'SSK044K1',
            description: 'Diseño militar en verde para los amantes de la aventura.',
            movement: 'Automático 4R34',
            diameter: '42.5mm',
            color: 'Verde militar',
            waterResistance: '100m',
            price: 385,
            currency: 'EUR',
            stock: 8,
            category: '5 Sports GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            slug: 'seiko-ssc911p1',
            name: 'Prospex Speedtimer Black',
            brand: 'Seiko',
            series: 'Prospex SSC',
            reference: 'SSC911P1',
            description: 'Cronógrafo solar Speedtimer con diseño clásico en negro.',
            movement: 'Solar V192',
            diameter: '41mm',
            color: 'Negro',
            waterResistance: '100m',
            price: 595,
            currency: 'EUR',
            stock: 4,
            category: 'Prospex SSC',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            slug: 'seiko-ssc927p1',
            name: 'Prospex Speedtimer Blue',
            brand: 'Seiko',
            series: 'Prospex SSC',
            reference: 'SSC927P1',
            description: 'Cronógrafo solar con esfera azul profundo, elegante y funcional.',
            movement: 'Solar V192',
            diameter: '41mm',
            color: 'Azul',
            waterResistance: '100m',
            price: 595,
            currency: 'EUR',
            stock: 3,
            category: 'Prospex SSC',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            slug: 'seiko-ssc935p1',
            name: 'Prospex Speedtimer Green',
            brand: 'Seiko',
            series: 'Prospex SSC',
            reference: 'SSC935P1',
            description: 'Versión verde del Speedtimer, audaz y contemporáneo.',
            movement: 'Solar V192',
            diameter: '41mm',
            color: 'Verde',
            waterResistance: '100m',
            price: 615,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SSC',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            slug: 'seiko-ssc947p1',
            name: 'Prospex Speedtimer Panda',
            brand: 'Seiko',
            series: 'Prospex SSC',
            reference: 'SSC947P1',
            description: 'Diseño Panda exclusivo con esfera blanca y subdiales negros.',
            movement: 'Solar V192',
            diameter: '41mm',
            color: 'Blanco/Negro',
            waterResistance: '100m',
            price: 625,
            currency: 'EUR',
            stock: 1,
            category: 'Prospex SSC',
            isNew: 0,
            isExclusive: 1,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            slug: 'seiko-spb149j1',
            name: 'Prospex Diver GMT Blue',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB149J1',
            description: 'Reloj de buceo GMT premium con esfera azul y movimiento automático.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Azul',
            waterResistance: '200m',
            price: 1195,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            slug: 'seiko-spb143j1',
            name: 'Prospex Diver GMT Pepsi',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB143J1',
            description: 'Reloj de buceo GMT con bisel Pepsi rojo y azul, clásico atemporal.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Rojo/Azul',
            waterResistance: '200m',
            price: 1150,
            currency: 'EUR',
            stock: 3,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            slug: 'seiko-spb213j1',
            name: 'Prospex Diver GMT Black',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB213J1',
            description: 'Versión negra del diver GMT, elegante y profesional.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Negro',
            waterResistance: '200m',
            price: 1175,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            slug: 'seiko-spb187j1',
            name: 'Prospex Diver GMT Forest',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB187J1',
            description: 'Nueva versión en verde bosque, diseño fresco y moderno.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Verde',
            waterResistance: '200m',
            price: 1225,
            currency: 'EUR',
            stock: 1,
            category: 'Prospex SPB GMT',
            isNew: 1,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            slug: 'seiko-spb207j1',
            name: 'Prospex Diver GMT Premium',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB207J1',
            description: 'Versión premium con esfera azul profundo y acabados refinados.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Azul profundo',
            waterResistance: '200m',
            price: 1295,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            slug: 'seiko-spb299j1',
            name: 'Prospex Diver GMT Compact',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB299J1',
            description: 'Versión compacta de 42mm, perfecta para muñecas más pequeñas.',
            movement: 'Automático 6R54',
            diameter: '42mm',
            color: 'Negro',
            waterResistance: '200m',
            price: 1165,
            currency: 'EUR',
            stock: 3,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            slug: 'seiko-spb451j1',
            name: 'Prospex Diver GMT Limited',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB451J1',
            description: 'Edición limitada con acabado DLC negro, exclusivo y resistente.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Negro DLC',
            waterResistance: '200m',
            price: 1350,
            currency: 'EUR',
            stock: 1,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 1,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            slug: 'seiko-spb297j1',
            name: 'Prospex Diver GMT Grey',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB297J1',
            description: 'Elegante versión gris, versátil y sofisticado.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Gris',
            waterResistance: '200m',
            price: 1185,
            currency: 'EUR',
            stock: 4,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            slug: 'seiko-spb453j1',
            name: 'Prospex Diver GMT Root Beer',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB453J1',
            description: 'Bisel Root Beer en marrón, diseño vintage y distinguido.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Marrón',
            waterResistance: '200m',
            price: 1245,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            slug: 'seiko-spb383j1',
            name: 'Prospex Diver GMT Cobalt',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB383J1',
            description: 'Vibrante azul cobalto, llamativo y deportivo.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Azul cobalto',
            waterResistance: '200m',
            price: 1315,
            currency: 'EUR',
            stock: 2,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            slug: 'seiko-spb381j1',
            name: 'Prospex Diver GMT Emerald',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB381J1',
            description: 'Hermoso verde esmeralda, elegante y distintivo.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Verde esmeralda',
            waterResistance: '200m',
            price: 1275,
            currency: 'EUR',
            stock: 3,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 1,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            slug: 'seiko-spb439j1',
            name: 'Prospex Diver GMT Elite',
            brand: 'Seiko',
            series: 'Prospex SPB GMT',
            reference: 'SPB439J1',
            description: 'Versión elite bicolor en negro y plata, máxima sofisticación.',
            movement: 'Automático 6R54',
            diameter: '44mm',
            color: 'Negro/Plata',
            waterResistance: '200m',
            price: 1335,
            currency: 'EUR',
            stock: 1,
            category: 'Prospex SPB GMT',
            isNew: 0,
            isExclusive: 0,
            isFeatured: 0,
            images: JSON.stringify(['/images/products/placeholder-watch.webp']),
            features: null,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 29 Seiko watches inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});