const sampleProducts = [
  // ——— SEIKO 5 SPORTS GMT (SSK) ———
  {
    slug: 'seiko-ssk003k1',
    name: 'Seiko 5 Sports GMT Black',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK003K1',
    description: 'Clásico negro con calibre 4R34 y bisel 24 h: robusto, preciso y listo para viajar.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Negro',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 5,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 1,
    images: JSON.stringify(['/images/products/SSK003K1.png']),
    features: null,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    slug: 'seiko-ssk001k1',
    name: 'Seiko 5 Sports GMT Blue',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK001K1',
    description: 'Azul profundo con aguja GMT: estilo diario y fiabilidad mecánica.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Azul',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 4,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK001K1.png']),
    features: null,
    createdAt: new Date('2024-01-16').toISOString(),
    updatedAt: new Date('2024-01-16').toISOString(),
  },
  {
    slug: 'seiko-ssk005k1',
    name: 'Seiko 5 Sports GMT Green',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK005K1',
    description: 'Verde con personalidad y bisel 24 h: el GMT versátil de Seiko.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Verde',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 3,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK005K1.png']),
    features: null,
    createdAt: new Date('2024-01-17').toISOString(),
    updatedAt: new Date('2024-01-17').toISOString(),
  },
  {
    slug: 'seiko-ssk021k1',
    name: 'Seiko 5 Sports GMT Gold',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK021K1',
    description: 'Acabado dorado que destaca, con el fiable 4R34 en su interior.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Dorado',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 2,
    category: '5 Sports GMT',
    isNew: 1,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK021K1.png']),
    features: null,
    createdAt: new Date('2024-01-18').toISOString(),
    updatedAt: new Date('2024-01-18').toISOString(),
  },
  {
    slug: 'seiko-ssk035k1',
    name: 'Seiko 5 Sports GMT Urban Grey',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK035K1',
    description: 'Gris urbano, resistente y listo para todo con función GMT.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Gris',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 6,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK035K1.png']),
    features: null,
    createdAt: new Date('2024-01-19').toISOString(),
    updatedAt: new Date('2024-01-19').toISOString(),
  },
  {
    slug: 'seiko-ssk033k1',
    name: 'Seiko 5 Sports GMT White',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK033K1',
    description: 'Esfera blanca legible y estética atemporal con aguja GMT.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Blanco',
    waterResistance: '100m',
    price: 325,
    currency: 'EUR',
    stock: 4,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK033K1.png']),
    features: null,
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    slug: 'seiko-ssk031k1',
    name: 'Seiko 5 Sports GMT Champagne',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK031K1',
    description: 'Tono champagne con ADN Seiko 5 y bisel 24 h. Elegante a diario.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Champagne',
    waterResistance: '100m',
    price: 480,
    currency: 'EUR',
    stock: 3,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK031K1.png']),
    features: null,
    createdAt: new Date('2024-01-21').toISOString(),
    updatedAt: new Date('2024-01-21').toISOString(),
  },
  {
    slug: 'seiko-ssk029k1',
    name: 'Seiko 5 Sports GMT DLC Black',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK029K1',
    description: 'Acabado DLC negro para máxima presencia y resistencia.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Negro DLC',
    waterResistance: '100m',
    price: 425,
    currency: 'EUR',
    stock: 2,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK029K1.png']),
    features: null,
    createdAt: new Date('2024-01-22').toISOString(),
    updatedAt: new Date('2024-01-22').toISOString(),
  },
  {
    slug: 'seiko-ssk043k1',
    name: 'Seiko 5 Sports GMT Multicolor',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK043K1',
    description: 'Un toque de color sin renunciar a la fiabilidad del 4R34.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Multicolor',
    waterResistance: '100m',
    price: 425,
    currency: 'EUR',
    stock: 5,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 1,
    images: JSON.stringify(['/images/products/SSK043K1.png']),
    features: null,
    createdAt: new Date('2024-01-23').toISOString(),
    updatedAt: new Date('2024-01-23').toISOString(),
  },
  {
    slug: 'seiko-ssk019k1',
    name: 'Seiko 5 Sports GMT Pepsi',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK019K1',
    description: 'Bisel azul/rojo icónico. Espíritu viajero con calibre 4R34.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Azul/Rojo',
    waterResistance: '100m',
    price: 425,
    currency: 'EUR',
    stock: 7,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK019K1.png']),
    features: null,
    createdAt: new Date('2024-01-24').toISOString(),
    updatedAt: new Date('2024-01-24').toISOString(),
  },
  {
    slug: 'seiko-ssk044k1',
    name: 'Seiko 5 Sports GMT Adventure',
    brand: 'Seiko',
    series: '5 Sports GMT',
    reference: 'SSK044K1',
    description: 'Verde militar con ADN aventurero. Fiel, cómodo y resistente.',
    movement: 'Automático 4R34',
    diameter: '42.5mm',
    color: 'Verde militar',
    waterResistance: '100m',
    price: 425,
    currency: 'EUR',
    stock: 8,
    category: '5 Sports GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSK044K1.png']),
    features: null,
    createdAt: new Date('2024-01-27').toISOString(),
    updatedAt: new Date('2024-01-27').toISOString(),
  },

  // ——— PROSPEX SSC SPEEDTIMER ———
  {
    slug: 'seiko-ssc911p1',
    name: 'Seiko Prospex Speedtimer Black',
    brand: 'Seiko',
    series: 'Prospex SSC',
    reference: 'SSC911P1',
    description: 'Cronógrafo solar V192: precisión y presencia con cero mantenimiento.',
    movement: 'Solar V192',
    diameter: '41mm',
    color: 'Negro',
    waterResistance: '100m',
    price: 595,
    currency: 'EUR',
    stock: 4,
    category: 'Prospex SSC',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 1,
    images: JSON.stringify(['/images/products/SSC911P1.png']),
    features: null,
    createdAt: new Date('2024-01-28').toISOString(),
    updatedAt: new Date('2024-01-28').toISOString(),
  },
  {
    slug: 'seiko-ssc947p1',
    name: 'Seiko Prospex Speedtimer Panda',
    brand: 'Seiko',
    series: 'Prospex SSC',
    reference: 'SSC947P1',
    description: 'Icono “Panda” con tecnología solar: estilo potente y exactitud constante.',
    movement: 'Solar V192',
    diameter: '41mm',
    color: 'Blanco/Negro',
    waterResistance: '100m',
    price: 595,
    currency: 'EUR',
    stock: 1,
    category: 'Prospex SSC',
    isNew: 0,
    isExclusive: 1,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SSC947P1.png']),
    features: null,
    createdAt: new Date('2024-01-31').toISOString(),
    updatedAt: new Date('2024-01-31').toISOString(),
  },

  // ——— PROSPEX SPB GMT (SPBXJ1) ———
  
  {
    slug: 'seiko-spb297j1',
    name: 'Seiko Prospex Diver GMT Grey',
    brand: 'Seiko',
    series: 'Prospex SPB GMT',
    reference: 'SPB297J1',
    description: 'Tono gris elegante con corazón 6R54 y 200 m: listo para todo.',
    movement: 'Automático 6R54',
    diameter: '44mm',
    color: 'Gris',
    waterResistance: '200m',
    price: 995,
    currency: 'EUR',
    stock: 4,
    category: 'Prospex SPB GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SPB297J1.png']),
    features: null,
    createdAt: new Date('2024-02-08').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
  },

  // ——— NUEVO EXTRA (pedido tuyo) ———
  {
    slug: 'seiko-spb485j1',
    name: 'Seiko Prospex Diver GMT Silver',
    brand: 'Seiko',
    series: 'Prospex SPB GMT',
    reference: 'SPB485J1',
    description: 'Edición de estética plata con 6R54: sólido, cómodo y muy versátil.',
    movement: 'Automático 6R54',
    diameter: '44mm',
    color: 'Plata',
    waterResistance: '200m',
    price: 990,
    currency: 'EUR',
    stock: 2,
    category: 'Prospex SPB GMT',
    isNew: 0,
    isExclusive: 0,
    isFeatured: 0,
    images: JSON.stringify(['/images/products/SPB485J1.png']),
    features: null,
    createdAt: new Date('2024-02-13').toISOString(),
    updatedAt: new Date('2024-02-13').toISOString(),
  },
];
      diameter: '42.5mm',
      color: 'Dorado',
      waterResistance: '100m',
      price: 325,
      currency: 'EUR',
      stock: 2,
      category: '5 Sports GMT',
      isNew: 1,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-18').toISOString(),
      updatedAt: new Date('2024-01-18').toISOString(),
    },
    {
      slug: 'seiko-ssk035k1',
      name: '5 Sports GMT Urban',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK035K1',
      description: 'Look urbano y fiable: el GMT que acompaña tu ritmo diario.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Gris',
      waterResistance: '100m',
      price: 325,
      currency: 'EUR',
      stock: 6,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-19').toISOString(),
      updatedAt: new Date('2024-01-19').toISOString(),
    },
    {
      slug: 'seiko-ssk033k1',
      name: '5 Sports GMT White',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK033K1',
      description: 'Esfera clara, legibilidad total y un GMT que nunca falla.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Blanco',
      waterResistance: '100m',
      price: 325,
      currency: 'EUR',
      stock: 4,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-20').toISOString(),
      updatedAt: new Date('2024-01-20').toISOString(),
    },
    {
      slug: 'seiko-ssk031k1',
      name: '5 Sports GMT Champagne',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK031K1',
      description: 'Tono champagne con ADN Seiko 5: elegancia diaria con función GMT.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Champagne',
      waterResistance: '100m',
      price: 480,
      currency: 'EUR',
      stock: 3,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-21').toISOString(),
      updatedAt: new Date('2024-01-21').toISOString(),
    },
    {
      slug: 'seiko-ssk029k1',
      name: '5 Sports GMT DLC',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK029K1',
      description: 'Acabado DLC para un GMT más rotundo, resistente y con presencia.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Negro DLC',
      waterResistance: '100m',
      price: 425,
      currency: 'EUR',
      stock: 2,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-22').toISOString(),
      updatedAt: new Date('2024-01-22').toISOString(),
    },
    {
      slug: 'seiko-ssk043k1',
      name: '5 Sports GMT Multicolor',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK043K1',
      description: 'Un toque de color sin perder la fiabilidad del 4R34 y 100 m.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Multicolor',
      waterResistance: '100m',
      price: 425,
      currency: 'EUR',
      stock: 5,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 1,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-23').toISOString(),
      updatedAt: new Date('2024-01-23').toISOString(),
    },
    {
      slug: 'seiko-ssk019k1',
      name: '5 Sports GMT Pepsi',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK019K1',
      description: 'Bisel bicolor icónico y calibre 4R34: puro espíritu viajero.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Azul/Rojo',
      waterResistance: '100m',
      price: 425,
      currency: 'EUR',
      stock: 7,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-24').toISOString(),
      updatedAt: new Date('2024-01-24').toISOString(),
    },
    {
      slug: 'seiko-ssk017k1',
      name: '5 Sports GMT Batman',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK017K1',
      description: 'Azul/negro con carácter y la utilidad de un GMT auténtico.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Azul/Negro',
      waterResistance: '100m',
      price: 425,
      currency: 'EUR',
      stock: 6,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-25').toISOString(),
      updatedAt: new Date('2024-01-25').toISOString(),
    },
    {
      slug: 'seiko-ssk027k1',
      name: '5 Sports GMT Steel',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK027K1',
      description: 'Acero integral y estética tool-watch con función GMT.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Acero',
      waterResistance: '100m',
      price: 899,
      currency: 'EUR',
      stock: 3,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-26').toISOString(),
      updatedAt: new Date('2024-01-26').toISOString(),
    },
    {
      slug: 'seiko-ssk044k1',
      name: '5 Sports GMT Adventure',
      brand: 'Seiko',
      series: '5 Sports GMT',
      reference: 'SSK044K1',
      description: 'Verde con ADN aventurero: el GMT ideal para escapadas.',
      movement: 'Automático 4R34',
      diameter: '42.5mm',
      color: 'Verde militar',
      waterResistance: '100m',
      price: 425,
      currency: 'EUR',
      stock: 8,
      category: '5 Sports GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-27').toISOString(),
      updatedAt: new Date('2024-01-27').toISOString(),
    },

    // ——— PROSPEX SSC SPEEDTIMER ———
    {
      slug: 'seiko-ssc911p1',
      name: 'Prospex Speedtimer Black',
      brand: 'Seiko',
      series: 'Prospex SSC',
      reference: 'SSC911P1',
      description: 'Cronógrafo solar V192: precisión, diseño clásico y cero mantenimiento.',
      movement: 'Solar V192',
      diameter: '41mm',
      color: 'Negro',
      waterResistance: '100m',
      price: 545,
      currency: 'EUR',
      stock: 4,
      category: 'Prospex SSC',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 1,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-28').toISOString(),
      updatedAt: new Date('2024-01-28').toISOString(),
    },
    {
      slug: 'seiko-ssc927p1',
      name: 'Prospex Speedtimer Blue',
      brand: 'Seiko',
      series: 'Prospex SSC',
      reference: 'SSC927P1',
      description: 'Esfera azul con energía solar: deporte y elegancia en un solo cronógrafo.',
      movement: 'Solar V192',
      diameter: '41mm',
      color: 'Azul',
      waterResistance: '100m',
      price: 545,
      currency: 'EUR',
      stock: 3,
      category: 'Prospex SSC',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-29').toISOString(),
      updatedAt: new Date('2024-01-29').toISOString(),
    },
    {
      slug: 'seiko-ssc935p1',
      name: 'Prospex Speedtimer Green',
      brand: 'Seiko',
      series: 'Prospex SSC',
      reference: 'SSC935P1',
      description: 'Verde contemporáneo y carga solar: rendimiento diario sin complicaciones.',
      movement: 'Solar V192',
      diameter: '41mm',
      color: 'Verde',
      waterResistance: '100m',
      price: 545,
      currency: 'EUR',
      stock: 2,
      category: 'Prospex SSC',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-30').toISOString(),
      updatedAt: new Date('2024-01-30').toISOString(),
    },
    {
      slug: 'seiko-ssc947p1',
      name: 'Prospex Speedtimer Panda',
      brand: 'Seiko',
      series: 'Prospex SSC',
      reference: 'SSC947P1',
      description: 'Icono “Panda” con tecnología solar: estilo fuerte y exactitud constante.',
      movement: 'Solar V192',
      diameter: '41mm',
      color: 'Blanco/Negro',
      waterResistance: '100m',
      price: 595,
      currency: 'EUR',
      stock: 1,
      category: 'Prospex SSC',
      isNew: 0,
      isExclusive: 1,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-01-31').toISOString(),
      updatedAt: new Date('2024-01-31').toISOString(),
    },

    // ——— PROSPEX SPB GMT (SPBXJ1 Series) ———
    {
      slug: 'seiko-spb149j1',
      name: 'Prospex Diver GMT Blue',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB149J1',
      description: 'Diver GMT 200 m con calibre 6R54 y zafiro: herramienta premium.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Azul',
      waterResistance: '200m',
      price: 850,
      currency: 'EUR',
      stock: 2,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 1,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-01').toISOString(),
      updatedAt: new Date('2024-02-01').toISOString(),
    },
    {
      slug: 'seiko-spb143j1',
      name: 'Prospex Diver GMT Pepsi',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB143J1',
      description: 'Bisel “Pepsi”, 200 m y 6R54: ADN Prospex con alma viajera.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Rojo/Azul',
      waterResistance: '200m',
      price: 890,
      currency: 'EUR',
      stock: 3,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-02').toISOString(),
      updatedAt: new Date('2024-02-02').toISOString(),
    },
    {
      slug: 'seiko-spb213j1',
      name: 'Prospex Diver GMT Black',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB213J1',
      description: 'Negro sobrio, 200 m y zafiro: el diver GMT para todo.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Negro',
      waterResistance: '200m',
      price: 965,
      currency: 'EUR',
      stock: 2,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-03').toISOString(),
      updatedAt: new Date('2024-02-03').toISOString(),
    },
    {
      slug: 'seiko-spb187j1',
      name: 'Prospex Diver GMT Forest',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB187J1',
      description: 'Verde bosque con 6R54 y 200 m: carácter, fiabilidad y comodidad.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Verde',
      waterResistance: '200m',
      price: 695,
      currency: 'EUR',
      stock: 1,
      category: 'Prospex SPB GMT',
      isNew: 1,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-04').toISOString(),
      updatedAt: new Date('2024-02-04').toISOString(),
    },
    {
      slug: 'seiko-spb207j1',
      name: 'Prospex Diver GMT Premium',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB207J1',
      description: 'Acabados superiores, zafiro y 6R54: diver GMT de alto nivel.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Azul profundo',
      waterResistance: '200m',
      price: 995,
      currency: 'EUR',
      stock: 2,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 1,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-05').toISOString(),
      updatedAt: new Date('2024-02-05').toISOString(),
    },
    {
      slug: 'seiko-spb299j1',
      name: 'Prospex Diver GMT Compact',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB299J1',
      description: 'Caja más contenida y la misma esencia Prospex: 200 m y 6R54.',
      movement: 'Automático 6R54',
      diameter: '42mm',
      color: 'Negro',
      waterResistance: '200m',
      price: 995,
      currency: 'EUR',
      stock: 3,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-06').toISOString(),
      updatedAt: new Date('2024-02-06').toISOString(),
    },
    {
      slug: 'seiko-spb451j1',
      name: 'Prospex Diver GMT Limited',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB451J1',
      description: 'Edición limitada con look contundente y especificaciones de referencia.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Negro DLC',
      waterResistance: '200m',
      price: 995,
      currency: 'EUR',
      stock: 1,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 1,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-07').toISOString(),
      updatedAt: new Date('2024-02-07').toISOString(),
    },
    {
      slug: 'seiko-spb297j1',
      name: 'Prospex Diver GMT Grey',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB297J1',
      description: 'Tono gris elegante con corazón 6R54 y 200 m: listo para todo.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Gris',
      waterResistance: '200m',
      price: 995,
      currency: 'EUR',
      stock: 4,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-08').toISOString(),
      updatedAt: new Date('2024-02-08').toISOString(),
    },

    {
      slug: 'seiko-spb439j1',
      name: 'Prospex Diver GMT Elite',
      brand: 'Seiko',
      series: 'Prospex SPB GMT',
      reference: 'SPB439J1',
      description: 'Bicolor con carácter y especificaciones de referencia: un diver total.',
      movement: 'Automático 6R54',
      diameter: '44mm',
      color: 'Negro/Plata',
      waterResistance: '200m',
      price: 1395,
      currency: 'EUR',
      stock: 1,
      category: 'Prospex SPB GMT',
      isNew: 0,
      isExclusive: 0,
      isFeatured: 0,
      images: JSON.stringify(['/images/products/placeholder-watch.webp']),
      features: null,
      createdAt: new Date('2024-02-12').toISOString(),
      updatedAt: new Date('2024-02-12').toISOString(),
    },
  ];

  await db.insert(products).values(sampleProducts);
  console.log('✅ Products seeder completed successfully - 29 Seiko watches inserted (prices aligned to catalog)');
}

main().catch((error) => {
  console.error('❌ Seeder failed:', error);
});
